#ifndef LIBQTEXTENSIONS_GLOBAL_H
#define LIBQTEXTENSIONS_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(LIBQTEXTENSIONS_LIBRARY)
#  define LIBQTEXTENSIONS_EXPORT Q_DECL_EXPORT
#else
#  define LIBQTEXTENSIONS_EXPORT Q_DECL_IMPORT
#endif

#endif // LIBQTEXTENSIONS_GLOBAL_H
